apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: hospital-management
spec:
  type: ClusterIP
  selector:
    app: ho-ma-auth
  ports:
  - port: 8001
    name: auth-port
    targetPort: 8001
