apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv
  namespace: hospital-management
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: redis-local-storage
  hostPath:
    path: "/storage/data1"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
  namespace: hospital-management
spec:
  storageClassName: redis-local-storage
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
