apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: hospital-management
spec:
  type: ClusterIP
  selector:
    app: ho-ma-redis
  ports:
  - port: 6379
    name: redis-port
    targetPort: 6379
