apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: redis-local-storage
provisioner: kubernetes.io/aws-ebs
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
reclaimPolicy: Delete