apiVersion: v1
kind: Service
metadata:
  name: rabbit-service
  namespace: hospital-management
spec:
  type: NodePort
  selector:
    app: ho-ma-rabit
  ports:
  - port: 5672
    targetPort: 5672
    name: rabbit-port
    protocol: TCP
  - port: 15672
    targetPort: 15672
    name: rabbit-mgmt
    protocol: TCP
