apiVersion: v1
kind: Service
metadata:
  name: appointment-service
  namespace: hospital-management
spec:
  type: ClusterIP
  selector:
    app: ho-ma-appointment
  ports:
  - port: 8003
    targetPort: 8003
    protocol: TCP
    name: appointment-port
