apiVersion: v1
kind: Service
metadata:
  name: users-service
  namespace: hospital-management
spec:
  type: ClusterIP
  selector:
    app: ho-ma-users
  ports:
  - port: 8002
    targetPort: 8002
    protocol: TCP
    name: users-port
