apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  namespace: hospital-management
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: mysql-local-storage
  hostPath:
   path: "/mnt/mysql-data"
   type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: hospital-management
spec:
  storageClassName: mysql-local-storage
  resources:
    requests:
      storage: 3Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce

  