apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: hospital-management
spec:
  type: ClusterIP
  selector:
    app: ho-ma-mysql
  ports:
  - port: 3306
    name: msyql-port
    targetPort: 3306
