apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mysql-local-storage
provisioner: kubernetes.io/aws-ebs
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer