apiVersion: apps/v1
kind: Deployment
metadata:
  name: ho-ma-elastic
  namespace: hospital-management
spec:
  selector:
    matchLabels:
      app: ho-ma-elastic
  strategy:
   type: Recreate
  template:
    metadata:
      labels:
        app: ho-ma-elastic
    spec:
      initContainers:
      - name: busy-elastic
        image: busybox
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: ho-ma-elastic-storage
          mountPath: /usr/share/elasticsearch/data
        command: ['sh', '-c', "chown -R 1000:1000 /usr/share/elasticsearch/data"]
      containers:
      - name: ho-ma-elastic
        image: docker.elastic.co/elasticsearch/elasticsearch:8.14.3
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "2Gi"
            cpu: "1500m"
          requests:
            memory: "2Gi"
            cpu: "250m"
        env:
        - name: discovery.type
          value: single-node
        - name: ES_JAVA_OPTS
          value: '-Xmx1g -Xms1g'
        - name: bootstrap.memory_lock
          value: 'true'
        - name: xpack.security.enabled
          value: 'false'
        - name: xpack.security.http.ssl.enabled
          value: 'false'
        - name: xpack.security.transport.ssl.enabled
          value: 'false'
        - name: xpack.security.authc.api_key.enabled
          value: 'true'
        - name: xpack.monitoring.collection.enabled
          value: 'true'
        - name: xpack.security.enrollment.enabled
          value: 'true'
        - name: xpack.security.authc.token.enabled
          value: 'true'
        ports:
        - name: ho-ma-elastic
          containerPort: 9200
        volumeMounts:
        - name: ho-ma-elastic-storage
          mountPath: /usr/share/elasticsearch/data
          subPath: data
      volumes:
      - name: ho-ma-elastic-storage
        persistentVolumeClaim:
          claimName: mo-ha-pvc
