apiVersion: v1
kind: PersistentVolume
metadata:
  name: mo-ha-pv
  namespace: hospital-management
spec:
  storageClassName: ho-ma-elastic-storage
  capacity:
    storage: 6Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mo-ha-pvc
  namespace: hospital-management
spec:
  storageClassName: ho-ma-elastic-storage
  resources:
    requests:
      storage: 6Gi
  accessModes:
    - ReadWriteOnce